### ISSUE TITLE
The mass and weight properties of rigidbody are broken in Godot3.3

### ISSUE THREAD

**Issue by titangamingglt** [Bubutotti/godot-hockey#1]
If I want to increase the weight of the puck( Rigid body) , the value becomes null.

**Comment by bububirb** [comment]
Not sure if this is a Godot 3.3 issue, I added a `RigidBody2D` to a new scene and changed the weight. Changes to null.

**Comment by bububirb** [comment]
Fixed it. The weight is calculated based on the Gravity in the Project Settings. I reverted it to 1 and set the Gravity Vector to Vector2( 0, 0 ) instead.

**Comment by bububirb** [comment]
Try to change the weight now, it should work. However, there seems to be no difference when doing so, but I'll assume that this is normal.

**Comment by titangamingglt** [comment]
Thank you
